spring.profiles.default: dev
spring.config:
  import:
    - classpath:/application-rds.yml
    - classpath:/application-external.yml
    - classpath:/application-internal.yml
    - classpath:/application-s3.yml
    - optional:classpath:/application-secret.yml

server:
  port: 9700
  name: gofield-admin
  monitoring: 고필드 관리자

spring.data:
  web:
    pageable:
      default-page-size: 20
      one-indexed-parameters: true

spring:
  thymeleaf:
    cache: false
