spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${secret.database.url}
    username: ${secret.database.username}
    password: ${secret.database.password}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 1000
        query.in_clause_parameter_padding: true
        check_nullability: true
    open-in-view: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace