feign:
  client:
    config:
      default:
        loggerLevel: FULL

external:
  client:
    kakao:
      profile:
        base-url: https://kapi.kakao.com
        url: /v2/user/me
      token:
        base-url: https://kauth.kakao.com
        url: /oauth/token
    apple:
      profile:
        base-url: https://appleid.apple.com
        url: /auth/keys
    naver:
      sns:
        base-url: https://sens.apigw.ntruss.com
        url: ${secret.naver.sns.url}
      profile:
        base-url: https://openapi.naver.com
        url: /v1/nid/me
      token:
        base-url: https://nid.naver.com
        url: /oauth2.0/token
    slack:
      webhook:
        base-url: https://hooks.slack.com/services
    toss:
      payment:
        base-url: https://api.tosspayments.com
        url: /v1/payments



