feign:
  client:
    config:
      default:
        loggerLevel: FULL

external:
  client:
    kakao:
      profile:
        base-url: https://kapi.kakao.com
        url: /v2/user/me
      token:
        base-url: https://kauth.kakao.com
        url: /oauth/token
    apple:
      profile:
        base-url: https://appleid.apple.com
        url: /auth/keys
    naver:
      sns:
        base-url: https://sens.apigw.ntruss.com
        url: ${secret.naver.sns.url}
      profile:
        base-url: https://openapi.naver.com
        url: /v1/nid/me
      token:
        base-url: https://nid.naver.com
        url: /oauth2.0/token
    slack:
      webhook:
        base-url: https://hooks.slack.com/services/
        exception-url: ${secret.slack.exception-token}
        order-url: ${secret.slack.order-token}
        cancel-url: ${secret.slack.cancel-token}
        return-url: ${secret.slack.return-token}
        change-url: ${secret.slack.change-token}
        qna-url: ${secret.slack.qna-token}
    toss:
      payment:
        base-url: https://api.tosspayments.com
        create-url: /v1/payments
        approve-url: /v1/payments/confirm
        cancel-url: /v1/payments/{paymentKey}/cancel
        virtual-account-url: /v1/virtual-accounts
    tracker:
      delivery:
        base-url: https://apis.tracker.delivery
        tracker-url : /carriers/{carrierId}/tracks/{trackId}