feign:
  client:
    config:
      default:
        loggerLevel: FULL

internal:
  client:
    sms:
      base-url: https://sns.gofield.shop
      single:
        url: /sms/send
      bulk:
        url: /sms/send/bulk

