secret:
  jwt:
    secret:

  auth:
    callback_url:
    front_local_redirect_url:
    front_service_redirect_url:

  gofield:
    access_key:
    device_key:
    token_key:

  kakao:
    auth_url:
    client_id:
    client_secret:
    front_local_redirect_url:
    front_service_redirect_url:
  naver:
    auth_url:
    client_id:
    client_secret:
    front_local_redirect_url:
    front_service_redirect_url:
    cloud:
      client_id:
      client_secret:
    sns:
      url:
  sns:
    auth:

  cdn:
    url:
  sqs:
    topic:
      sms:

  payment:
    success:
      front_local_redirect_url:
      front_service_redirect_url:
    fail:
      front_local_redirect_url:
      front_service_redirect_url:

  database:
    url:
    username:
    password:

  aws:
    access-key:
    secret-key:
  toss:
    success-url:
    fail-url:

    secret-key:

  slack:
    token:
