spring.profiles.default: dev
spring.config:
  import:
    - classpath:/application-rds.yml
    - classpath:/application-external-dev.yml
    - classpath:/application-internal.yml
    - classpath:/application-s3.yml
    - classpath:/application-sqs.yml
    - optional:classpath:/application-secret.yml

server:
  port: 9090
  name: gofield-api-user
  monitoring: 고필드 사용자 api
  servlet:
    encoding:
      charset: UTF-8
      force: true


