cloud:
  aws:
    credentials:
      access-key: ${secret.aws.access-key}
      secret-key: ${secret.aws.secret-key}
    region:
      static: ap-northeast-2
    stack:
      auto: false

sqs:
  topic:
    sms: gofield-sms
    push:
      user: gofield-user-push
      admin: gofield-admin-push
      partner: gofield-partner-push