spring.profiles.default: dev
spring.config:
  import:
    - classpath:/application-external.yml
    - classpath:/application-sqs.yml
    - optional:classpath:/application-secret.yml

server:
  port: 9100
  name: gofield-sns
  monitoring: 고필드 SNS

