name:

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash

      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: aws ec2 ip, port open
        run: >
          aws ec2 authorize-security-group-ingress
          --group-name ${{ secrets.SECURITY_GROUP_NAME }}
          --protocol tcp
          --port ${{ secrets.REMOTE_SSH_PORT }}
          --cidr ${{ steps.ip.outputs.ipv4 }}/32
          --query "none"

      - name: Generate Config Files
        run:
          echo "${{ secrets.SECRET_USER_ENVIORNMENT }}" >> gofield-api-user-service/src/main/resources/application-secret.yml

      - name: (scp) gofield-backend folder to ec2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          source: "."
          target: "/opt/gofield-backend-user"

